<?php
/*
 * vim: ts=3 sw=3 et wrap co=100 go-=b
 */

require_once dirname(__FILE__) . '/lib/tom/php/utils/UtilsError.php';
require_once dirname(__FILE__) . '/lib/tom/php/utils/UtilsValidator.php';
require_once dirname(__FILE__) . '/php/database_connection.php';
require_once dirname(__FILE__) . '/php/utils/HtmlUtil.php';

UtilsError::initErrorAndExceptionHandler('log.txt');

$i = HtmlUtil::echoHtmlForHeaderAndReturnIndent('logLifts');

echo "$i<table id='subheading-table-1'>\n";
echo "$i <tbody>\n";
echo "$i  <tr>\n";
echo "$i   <td class='align-l'><span class='anchor-style'>TMac</span></td>\n";
echo "$i   <td class='align-c'><span class='anchor-style'></span></td>\n";
echo "$i   <td class='align-r'><span class='anchor-style'>Settings</span></td>\n";
echo "$i  </tr>\n";
echo "$i </tbody>\n";
echo "$i</table>\n";
echo "$i<table id='subheading-table-2'>\n";
echo "$i <tbody>\n";
echo "$i  <tr>\n";
echo "$i   <td class='align-l'><select><option>Load workout template</option></select></td>\n";
echo "$i   <td class='align-c'></td>\n";
echo "$i   <td class='align-r'><input type='button' value='Save workout as template'/></td>\n";
echo "$i  </tr>\n";
echo "$i </tbody>\n";
echo "$i</table>\n";
echo "$i<div id='log-table-wrapper'>\n";
echo "$i <table id='log-table'>\n";
echo "$i  <thead>\n";
echo "$i   <tr><th colspan='6' class='main-heading align-c'>Workout #31 - 2013-06-15</th></tr>\n";
echo "$i   <tr>\n";
echo "$i    <th rowspan='2' class='column-heading'>Exercise<br/>Name</th>\n";
echo "$i    <th rowspan='2' class='column-heading'>Weight<br/>(";
echo        "<span class='anchor-style' title='Click to toggle between kilograms and pounds'>";
echo        "kg</span>)</th>\n";
echo "$i    <th rowspan='2' class='column-heading'>Reps</th>\n";
echo "$i    <th colspan='2' class='column-heading'>Time</th>\n";
echo "$i    <th rowspan='2' class='column-heading'>Done</th>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <th class='column-heading'>Target</th>\n";
echo "$i    <th class='column-heading'>Actual</th>\n";
echo "$i   </tr>\n";
echo "$i  </thead>\n";
echo "$i  <tfoot>\n";
echo "$i   <tr>\n";
echo "$i    <td colspan='6' class='add-row-td'><input type='button' value='Add row'/></td>\n";
echo "$i   </tr>\n";
echo "$i  </tfoot>\n";
echo "$i  <tbody>\n";
echo "$i   <tr>\n";
echo "$i    <td rowspan='7'><select><option>Squat</option></select>\n";
echo "$i    <td><input type='text' value='20'/></td>\n";
echo "$i    <td><input type='text' value='10'/></td>\n";
echo "$i    <td class='align-r time-td'>+1:00</td>\n";
echo "$i    <td class='align-r time-td'>+0:54</td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='50'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+2:00</td>\n";
echo "$i    <td class='align-r time-td'>+1:54</td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='70'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+2:30</td>\n";
echo "$i    <td class='align-r time-td'>+2:44</td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='100'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+3:00</td>\n";
echo "$i    <td class='align-r time-td'>+3:06</td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='120'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+4:00</td>\n";
echo "$i    <td class='align-r time-td'>+4:20</td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='120'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+4:00</td>\n";
echo "$i    <td class='align-r time-td'>+4:32</td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='120'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+4:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td rowspan='6'><select><option>Shoulder Press</option></select>\n";
echo "$i    <td><input type='text' value='0'/></td>\n";
echo "$i    <td><input type='text' value='10'/></td>\n";
echo "$i    <td class='align-r time-td'>+1:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='20'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+2:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='40'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+2:30</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='60'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+4:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='60'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+4:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='60'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+4:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td rowspan='6'><select><option>Power Clean</option></select>\n";
echo "$i    <td><input type='text' value='0'/></td>\n";
echo "$i    <td><input type='text' value='10'/></td>\n";
echo "$i    <td class='align-r time-td'>+2:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='20'/></td>\n";
echo "$i    <td><input type='text' value='10'/></td>\n";
echo "$i    <td class='align-r time-td'>+2:30</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='50'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+3:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='80'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+4:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='80'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+4:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='80'/></td>\n";
echo "$i    <td><input type='text' value='5'/></td>\n";
echo "$i    <td class='align-r time-td'>+4:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td rowspan='3'><select><option>Wide Grip Chin</option></select>\n";
echo "$i    <td><input type='text' value='0'/></td>\n";
echo "$i    <td><input type='text' value='10'/></td>\n";
echo "$i    <td class='align-r time-td'>+4:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='0'/></td>\n";
echo "$i    <td><input type='text' value='10'/></td>\n";
echo "$i    <td class='align-r time-td'>+4:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i   <tr>\n";
echo "$i    <td><input type='text' value='0'/></td>\n";
echo "$i    <td><input type='text' value='10'/></td>\n";
echo "$i    <td class='align-r time-td'>+4:00</td>\n";
echo "$i    <td class='align-r time-td'></td>\n";
echo "$i    <td class='align-c done-td'><input type='checkbox'/></td>\n";
echo "$i   </tr>\n";
echo "$i  </tbody>\n";
echo "$i </table>\n";
echo "$i</div>\n";

echo "$i<div id='notes-div'>\n";
echo "$i <h2>Notes</h2>\n";
echo "$i <textarea></textarea>\n";
echo "$i</div>\n";

HtmlUtil::echoHtmlForFooter();
?>
